%bcond_without tests
%bcond_without weak_deps

%global __os_install_post %(echo '%{__os_install_post}' | sed -e 's!/usr/lib[^[:space:]]*/brp-python-bytecompile[[:space:]].*$!!g')
%global __provides_exclude_from ^/opt/ros/kilted/.*$
%global __requires_exclude_from ^/opt/ros/kilted/.*$

Name:           ros-kilted-mp2p-icp
Version:        2.4.1
Release:        1%{?dist}%{?release_suffix}
Summary:        ROS mp2p_icp package

License:        BSD-3-Clause
URL:            https://github.com/MOLAorg/mp2p_icp
Source0:        %{name}-%{version}.tar.gz

Requires:       ros-kilted-mola-common
Requires:       ros-kilted-mola-imu-preintegration
Requires:       ros-kilted-mrpt-libbase
Requires:       ros-kilted-mrpt-libgui
Requires:       ros-kilted-mrpt-libmaps
Requires:       ros-kilted-mrpt-libobs
Requires:       ros-kilted-mrpt-libposes
Requires:       ros-kilted-mrpt-libtclap
Requires:       tbb-devel
Requires:       ros-kilted-ros-workspace
BuildRequires:  cmake3
BuildRequires:  ros-kilted-mola-common
BuildRequires:  ros-kilted-mola-imu-preintegration
BuildRequires:  ros-kilted-mrpt-libbase
BuildRequires:  ros-kilted-mrpt-libgui
BuildRequires:  ros-kilted-mrpt-libmaps
BuildRequires:  ros-kilted-mrpt-libobs
BuildRequires:  ros-kilted-mrpt-libposes
BuildRequires:  ros-kilted-mrpt-libtclap
BuildRequires:  ros-kilted-ros-environment
BuildRequires:  tbb-devel
BuildRequires:  ros-kilted-ros-workspace
Provides:       %{name}-devel = %{version}-%{release}
Provides:       %{name}-doc = %{version}-%{release}
Provides:       %{name}-runtime = %{version}-%{release}

%description
A repertory of multi primitive-to-primitive (MP2P) ICP algorithms in C++

%prep
%autosetup -p1

%build
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree and source it.  It will set things like
# CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/kilted/setup.sh" ]; then . "/opt/ros/kilted/setup.sh"; fi
mkdir -p .obj-%{_target_platform} && cd .obj-%{_target_platform}
%cmake3 \
    -UINCLUDE_INSTALL_DIR \
    -ULIB_INSTALL_DIR \
    -USYSCONF_INSTALL_DIR \
    -USHARE_INSTALL_PREFIX \
    -ULIB_SUFFIX \
    -DCMAKE_INSTALL_PREFIX="/opt/ros/kilted" \
    -DCMAKE_PREFIX_PATH="/opt/ros/kilted" \
    -DSETUPTOOLS_DEB_LAYOUT=OFF \
%if !0%{?with_tests}
    -DBUILD_TESTING=OFF \
%endif
    ..

%make_build

%install
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree and source it.  It will set things like
# CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/kilted/setup.sh" ]; then . "/opt/ros/kilted/setup.sh"; fi
%make_install -C .obj-%{_target_platform}

%if 0%{?with_tests}
%check
# Look for a Makefile target with a name indicating that it runs tests
TEST_TARGET=$(%__make -qp -C .obj-%{_target_platform} | sed "s/^\(test\|check\):.*/\\1/;t f;d;:f;q0")
if [ -n "$TEST_TARGET" ]; then
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree and source it.  It will set things like
# CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/kilted/setup.sh" ]; then . "/opt/ros/kilted/setup.sh"; fi
CTEST_OUTPUT_ON_FAILURE=1 \
    %make_build -C .obj-%{_target_platform} $TEST_TARGET || echo "RPM TESTS FAILED"
else echo "RPM TESTS SKIPPED"; fi
%endif

%files
%license COPYING
/opt/ros/kilted

%changelog
* Tue Jan 27 2026 Jose-Luis Blanco-Claraco <joseluisblancoc@gmail.com> - 2.4.1-1
- Autogenerated by Bloom

* Wed Jan 21 2026 Jose-Luis Blanco-Claraco <joseluisblancoc@gmail.com> - 2.4.0-1
- Autogenerated by Bloom

* Wed Jan 14 2026 Jose-Luis Blanco-Claraco <joseluisblancoc@gmail.com> - 2.3.1-1
- Autogenerated by Bloom

* Thu Jan 08 2026 Jose-Luis Blanco-Claraco <joseluisblancoc@gmail.com> - 2.3.0-1
- Autogenerated by Bloom

* Tue Jan 06 2026 Jose-Luis Blanco-Claraco <joseluisblancoc@gmail.com> - 2.2.1-1
- Autogenerated by Bloom

* Sun Dec 28 2025 Jose-Luis Blanco-Claraco <joseluisblancoc@gmail.com> - 2.2.0-1
- Autogenerated by Bloom

* Fri Nov 28 2025 Jose-Luis Blanco-Claraco <joseluisblancoc@gmail.com> - 2.1.2-1
- Autogenerated by Bloom

* Sat Nov 08 2025 Jose-Luis Blanco-Claraco <joseluisblancoc@gmail.com> - 2.1.1-1
- Autogenerated by Bloom

* Tue Oct 28 2025 Jose-Luis Blanco-Claraco <joseluisblancoc@gmail.com> - 2.1.0-1
- Autogenerated by Bloom

* Mon Oct 13 2025 Jose-Luis Blanco-Claraco <joseluisblancoc@gmail.com> - 2.0.0-1
- Autogenerated by Bloom

* Tue Aug 26 2025 Jose-Luis Blanco-Claraco <joseluisblancoc@gmail.com> - 1.8.0-1
- Autogenerated by Bloom

* Fri Jun 20 2025 Jose-Luis Blanco-Claraco <joseluisblancoc@gmail.com> - 1.7.1-1
- Autogenerated by Bloom

* Mon Jun 02 2025 Jose-Luis Blanco-Claraco <joseluisblancoc@gmail.com> - 1.7.0-1
- Autogenerated by Bloom

* Tue Apr 22 2025 Jose-Luis Blanco-Claraco <joseluisblancoc@gmail.com> - 1.6.7-2
- Autogenerated by Bloom

* Thu Apr 03 2025 Jose-Luis Blanco-Claraco <joseluisblancoc@gmail.com> - 1.6.7-1
- Autogenerated by Bloom

* Wed Feb 26 2025 Jose-Luis Blanco-Claraco <joseluisblancoc@gmail.com> - 1.6.6-1
- Autogenerated by Bloom

* Tue Jan 28 2025 Jose-Luis Blanco-Claraco <joseluisblancoc@gmail.com> - 1.6.5-1
- Autogenerated by Bloom

* Wed Dec 18 2024 Jose-Luis Blanco-Claraco <joseluisblancoc@gmail.com> - 1.6.4-1
- Autogenerated by Bloom

* Mon Nov 11 2024 Jose-Luis Blanco-Claraco <joseluisblancoc@gmail.com> - 1.6.3-1
- Autogenerated by Bloom

* Sat Sep 14 2024 Jose-Luis Blanco-Claraco <joseluisblancoc@gmail.com> - 1.6.2-1
- Autogenerated by Bloom

* Mon Sep 09 2024 Jose-Luis Blanco-Claraco <joseluisblancoc@gmail.com> - 1.6.0-1
- Autogenerated by Bloom

* Tue Aug 27 2024 Jose-Luis Blanco-Claraco <joseluisblancoc@gmail.com> - 1.5.5-1
- Autogenerated by Bloom

* Tue Aug 20 2024 Jose-Luis Blanco-Claraco <joseluisblancoc@gmail.com> - 1.5.3-1
- Autogenerated by Bloom

* Wed Jul 24 2024 Jose-Luis Blanco-Claraco <joseluisblancoc@gmail.com> - 1.5.2-1
- Autogenerated by Bloom

* Wed Jul 03 2024 Jose-Luis Blanco-Claraco <joseluisblancoc@gmail.com> - 1.5.1-1
- Autogenerated by Bloom

* Fri Jun 21 2024 Jose-Luis Blanco-Claraco <joseluisblancoc@gmail.com> - 1.5.0-1
- Autogenerated by Bloom

* Tue Jun 11 2024 Jose-Luis Blanco-Claraco <joseluisblancoc@gmail.com> - 1.4.3-1
- Autogenerated by Bloom

* Tue May 28 2024 Jose-Luis Blanco-Claraco <joseluisblancoc@gmail.com> - 1.4.2-1
- Autogenerated by Bloom

* Sun May 19 2024 Jose-Luis Blanco-Claraco <joseluisblancoc@gmail.com> - 1.4.1-1
- Autogenerated by Bloom

* Mon May 06 2024 Jose-Luis Blanco-Claraco <joseluisblancoc@gmail.com> - 1.4.0-1
- Autogenerated by Bloom

* Tue Apr 30 2024 Jose-Luis Blanco-Claraco <joseluisblancoc@gmail.com> - 1.3.3-1
- Autogenerated by Bloom

* Mon Apr 22 2024 Jose-Luis Blanco-Claraco <joseluisblancoc@gmail.com> - 1.3.2-1
- Autogenerated by Bloom

* Tue Apr 16 2024 Jose-Luis Blanco-Claraco <joseluisblancoc@gmail.com> - 1.3.1-1
- Autogenerated by Bloom

* Thu Mar 14 2024 Jose-Luis Blanco-Claraco <joseluisblancoc@gmail.com> - 1.3.0-1
- Autogenerated by Bloom

* Wed Mar 06 2024 Jose-Luis Blanco-Claraco <joseluisblancoc@gmail.com> - 1.2.0-2
- Autogenerated by Bloom

