%bcond_without tests
%bcond_without weak_deps

%global __os_install_post %(echo '%{__os_install_post}' | sed -e 's!/usr/lib[^[:space:]]*/brp-python-bytecompile[[:space:]].*$!!g')
%global __provides_exclude_from ^/opt/ros/jazzy/.*$
%global __requires_exclude_from ^/opt/ros/jazzy/.*$

%global __cmake_in_source_build 1

Name:           ros-jazzy-mp2p-icp-core
Version:        3.0.0
Release:        1%{?dist}%{?release_suffix}
Summary:        ROS mp2p_icp_core package

License:        BSD-3-Clause
URL:            https://github.com/MOLAorg/mp2p_icp
Source0:        %{name}-%{version}.tar.gz

Requires:       cli11-devel
Requires:       eigen3-devel
Requires:       ros-jazzy-mola-common
Requires:       ros-jazzy-mola-imu-preintegration
Requires:       ros-jazzy-mrpt-containers
Requires:       ros-jazzy-mrpt-maps
Requires:       ros-jazzy-mrpt-obs
Requires:       ros-jazzy-mrpt-poses
Requires:       ros-jazzy-mrpt-rtti
Requires:       ros-jazzy-mrpt-serialization
Requires:       ros-jazzy-mrpt-system
Requires:       ros-jazzy-mrpt-tfest
Requires:       ros-jazzy-mrpt-topography
Requires:       tbb-devel
Requires:       ros-jazzy-ros-workspace
BuildRequires:  cli11-devel
BuildRequires:  cmake3
BuildRequires:  eigen3-devel
BuildRequires:  ros-jazzy-mola-common
BuildRequires:  ros-jazzy-mola-imu-preintegration
BuildRequires:  ros-jazzy-mrpt-containers
BuildRequires:  ros-jazzy-mrpt-maps
BuildRequires:  ros-jazzy-mrpt-obs
BuildRequires:  ros-jazzy-mrpt-poses
BuildRequires:  ros-jazzy-mrpt-rtti
BuildRequires:  ros-jazzy-mrpt-serialization
BuildRequires:  ros-jazzy-mrpt-system
BuildRequires:  ros-jazzy-mrpt-tfest
BuildRequires:  ros-jazzy-mrpt-topography
BuildRequires:  ros-jazzy-ros-environment
BuildRequires:  tbb-devel
BuildRequires:  ros-jazzy-ros-workspace
Provides:       %{name}-devel = %{version}-%{release}
Provides:       %{name}-doc = %{version}-%{release}
Provides:       %{name}-runtime = %{version}-%{release}

%description
C++ libraries for multi primitive-to-primitive (MP2P) ICP algorithms and point
cloud processing pipelines, plus headless CLI applications. No GUI/display
dependencies; see mp2p_icp_viz for the GUI apps.

%prep
%autosetup -p1

%build
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree and source it.  It will set things like
# CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/jazzy/setup.sh" ]; then . "/opt/ros/jazzy/setup.sh"; fi
mkdir -p .obj-%{_target_platform} && cd .obj-%{_target_platform}
%cmake3 \
    -UINCLUDE_INSTALL_DIR \
    -ULIB_INSTALL_DIR \
    -USYSCONF_INSTALL_DIR \
    -USHARE_INSTALL_PREFIX \
    -ULIB_SUFFIX \
    -DCMAKE_INSTALL_PREFIX="/opt/ros/jazzy" \
    -DCMAKE_PREFIX_PATH="/opt/ros/jazzy" \
    -DSETUPTOOLS_DEB_LAYOUT=OFF \
%if !0%{?with_tests}
    -DBUILD_TESTING=OFF \
%endif
    ..

%make_build

%install
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree and source it.  It will set things like
# CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/jazzy/setup.sh" ]; then . "/opt/ros/jazzy/setup.sh"; fi
%make_install -C .obj-%{_target_platform}

%if 0%{?with_tests}
%check
# Look for a Makefile target with a name indicating that it runs tests
TEST_TARGET=$(%__make -qp -C .obj-%{_target_platform} | sed "s/^\(test\|check\):.*/\\1/;t f;d;:f;q0")
if [ -n "$TEST_TARGET" ]; then
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree and source it.  It will set things like
# CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/jazzy/setup.sh" ]; then . "/opt/ros/jazzy/setup.sh"; fi
CTEST_OUTPUT_ON_FAILURE=1 \
    %make_build -C .obj-%{_target_platform} $TEST_TARGET || echo "RPM TESTS FAILED"
else echo "RPM TESTS SKIPPED"; fi
%endif

%files
%license COPYING
/opt/ros/jazzy

%changelog
* Mon Sep 28 2026 Jose-Luis Blanco-Claraco <joseluisblancoc@gmail.com> - 3.0.0-1
- Autogenerated by Bloom

* Tue Sep 15 2026 Jose-Luis Blanco-Claraco <joseluisblancoc@gmail.com> - 2.14.1-1
- Autogenerated by Bloom

* Sat Sep 05 2026 Jose-Luis Blanco-Claraco <joseluisblancoc@gmail.com> - 2.14.0-1
- Autogenerated by Bloom

* Tue Aug 25 2026 Jose-Luis Blanco-Claraco <joseluisblancoc@gmail.com> - 2.13.1-1
- Autogenerated by Bloom

* Fri Aug 21 2026 Jose-Luis Blanco-Claraco <joseluisblancoc@gmail.com> - 2.13.0-1
- Autogenerated by Bloom

* Fri Jul 10 2026 Jose-Luis Blanco-Claraco <joseluisblancoc@gmail.com> - 2.12.0-1
- Autogenerated by Bloom

