version: 2.1
jobs:
  gcc-u2404-mrpt-dev:
    docker:
      - image: ubuntu:24.04
    steps:
      - run:
          name: "Install dependencies"
          command: |
            export DEBIAN_FRONTEND=noninteractive
            export TZ=Etc/UTC
            apt-get update
            apt-get install build-essential cmake git -y
            apt-get install software-properties-common -y
            add-apt-repository ppa:joseluisblancoc/mrpt -y
            apt-get install libmrpt-dev -y
      - checkout
      - run:
          name: "Pull Submodules"
          command: |
            git submodule init
            git submodule update --remote
      - run:
          name: Generate cmake files
          command: cmake -H. -Bbuild
      - run: make -C build
      - run: make CTEST_OUTPUT_ON_FAILURE=1 test -C build
  #      - run: make gcov -C build
  #      - run: make -C build
  #      - run: bash <(curl -s https://codecov.io/bash) -X gcov -y .codecov.yml -s build
  gcc-u2404-mrpt-stable:
    docker:
      - image: ubuntu:24.04
    steps:
      - run:
          name: "Install dependencies"
          command: |
            export DEBIAN_FRONTEND=noninteractive
            export TZ=Etc/UTC
            apt-get update
            apt-get install build-essential cmake git -y
            apt-get install software-properties-common -y
            add-apt-repository ppa:joseluisblancoc/mrpt-stable -y
            apt-get install libmrpt-dev -y
      - checkout
      - run:
          name: "Pull Submodules"
          command: |
            git submodule init
            git submodule update --remote
      - run:
          name: Generate cmake files
          command: cmake -H. -Bbuild
      - run: make -C build
      - run: make CTEST_OUTPUT_ON_FAILURE=1 test -C build
  clang-u2404-mrpt-dev:
    docker:
      - image: ubuntu:24.04
    steps:
      - run:
          name: "Install dependencies"
          command: |
            export DEBIAN_FRONTEND=noninteractive
            export TZ=Etc/UTC
            apt-get update
            apt-get install build-essential cmake git -y
            apt-get install software-properties-common -y
            add-apt-repository ppa:joseluisblancoc/mrpt -y
            apt-get install libmrpt-dev -y
            apt-get install -y clang-18
      - checkout
      - run:
          name: "Pull Submodules"
          command: |
            git submodule init
            git submodule update --remote
      - run:
          name: Generate cmake files
          command: cmake -H. -Bbuild
          environment:
            CC: /usr/bin/clang-18
            CXX: /usr/bin/clang++-18
      - run: make -C build
      - run: make CTEST_OUTPUT_ON_FAILURE=1 test -C build
workflows:
  version: 2
  build:
    jobs:
      - gcc-u2404-mrpt-dev
      - gcc-u2404-mrpt-stable
      - clang-u2404-mrpt-dev
